name: Test Repository Integrity

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    # Run tests weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Bash
      run: |
        echo "Bash version:"
        bash --version
        
    - name: Install dependencies
      run: |
        echo "Checking for required tools..."
        which curl
        which sed
        which awk
        which grep
        which find
        which stat
        
    - name: Make scripts executable
      run: |
        chmod +x scripts/*.sh
        chmod +x *.sh
        
    - name: Run test suite
      run: |
        ./test.sh
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results.log
        
    - name: Comment on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          let testLog = '';
          try {
            testLog = fs.readFileSync('test-results.log', 'utf8');
          } catch (e) {
            testLog = 'Test log not found';
          }
          
          const comment = `## 🧪 Test Results
          
          ${testLog}
          
          ---
          *Tests run automatically on PR*`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          }); 